import validationInput from '../utils/validation.utils.ts';
import getArboMasterlist from '../persisters/getArboMasterlist.persisters.ts';
import { Request, Response } from 'express';
import { decrypt, encrypt } from '../utils/crypt.util.ts';
import { CryptGetArboMasterlistResModel } from '../model/crypt/getArboMasterlistCrypt.model.ts';
import { getArboMasterlistReqModel } from '../model/request/getArboMasterlistReq.model.ts';
import { getArboMasterlistResModel } from '../model/response/getArboMasterlistRes.model.ts';

const getArboMasterlistController = async (req: Request, res: Response): Promise<void> => {
  // Handles validation and throws if needed
  const arboMasterlistData = validationInput(getArboMasterlistReqModel, req.body);

  let arboMasterlist: CryptGetArboMasterlistResModel[] = [];

  if (Object.keys(req.body).length === 0) {
    const encryptedData = undefined;
    arboMasterlist = (await getArboMasterlist(encryptedData)) as [];
  } else {
    const encryptedData = [
      {
        id: arboMasterlistData.id,
        region_name: encrypt(arboMasterlistData.region_name),
        region_code: encrypt(arboMasterlistData.region_code),
        province_name: encrypt(arboMasterlistData.province_name),
        province_code: encrypt(arboMasterlistData.province_code),
        muncity_name: encrypt(arboMasterlistData.muncity_name),
        muncity_code: encrypt(arboMasterlistData.muncity_code),
        barangay_name: encrypt(arboMasterlistData.barangay_name),
        barangay_code: encrypt(arboMasterlistData.barangay_code),
        cd: encrypt(arboMasterlistData.cd),
        arc_type: encrypt(arboMasterlistData.arc_type),
        arc_id: encrypt(arboMasterlistData.arc_id),
        arc_name: encrypt(arboMasterlistData.arc_name),
        arc_cluster_name: encrypt(arboMasterlistData.arc_cluster_name),
        arbo_name: encrypt(arboMasterlistData.arbo_name),
        arbo_id: encrypt(arboMasterlistData.arbo_id),
        oma_level_2013: encrypt(arboMasterlistData.oma_level_2013),
        itema_status_2019: encrypt(arboMasterlistData.itema_status_2019),
        itema_level_2019: encrypt(arboMasterlistData.itema_level_2019),
        itema_status_current: encrypt(arboMasterlistData.itema_status_current),
        itema_level_current: encrypt(arboMasterlistData.itema_level_current),
        organization_status: encrypt(arboMasterlistData.organization_status),
        organization_type: encrypt(arboMasterlistData.organization_type),
        year_organized: encrypt(arboMasterlistData.year_organized),
        registering_agency: encrypt(arboMasterlistData.registering_agency),
        year_registration: encrypt(arboMasterlistData.year_registration),
        baseline_members: encrypt(arboMasterlistData.baseline_members),
        baseline_members_male: encrypt(arboMasterlistData.baseline_members_male),
        baseline_members_female: encrypt(arboMasterlistData.baseline_members_female),
        baseline_total_arbs: encrypt(arboMasterlistData.baseline_total_arbs),
        baseline_male_arbs: encrypt(arboMasterlistData.baseline_male_arbs),
        baseline_female_arbs: encrypt(arboMasterlistData.baseline_female_arbs),
        baseline_total_nonarbs: encrypt(arboMasterlistData.baseline_total_nonarbs),
        baseline_male_nonarbs: encrypt(arboMasterlistData.baseline_male_nonarbs),
        baseline_female_nonarbs: encrypt(arboMasterlistData.baseline_female_nonarbs),
        current_members: encrypt(arboMasterlistData.current_members),
        current_members_male: encrypt(arboMasterlistData.current_members_male),
        current_members_female: encrypt(arboMasterlistData.current_members_female),
        current_total_arbs: encrypt(arboMasterlistData.current_total_arbs),
        current_male_arbs: encrypt(arboMasterlistData.current_male_arbs),
        current_female_arbs: encrypt(arboMasterlistData.current_female_arbs),
        current_total_nonarbs: encrypt(arboMasterlistData.current_total_nonarbs),
        current_male_nonarbs: encrypt(arboMasterlistData.current_male_nonarbs),
        current_female_nonarbs: encrypt(arboMasterlistData.current_female_nonarbs),
        cbu_current: encrypt(arboMasterlistData.cbu_current),
        cbu_mem_current: encrypt(arboMasterlistData.cbu_mem_current),
        savings_current: encrypt(arboMasterlistData.savings_current),
        sav_mem_current: encrypt(arboMasterlistData.sav_mem_current),
        assets_current: encrypt(arboMasterlistData.assets_current),
        liabilities_current: encrypt(arboMasterlistData.liabilities_current),
        services_provided: encrypt(arboMasterlistData.services_provided),
        trainings_cap_dev: encrypt(arboMasterlistData.trainings_cap_dev),
        apcp: encrypt(arboMasterlistData.apcp),
        linksfarm: encrypt(arboMasterlistData.linksfarm),
        up_valuing: encrypt(arboMasterlistData.up_valuing),
        cp_wash: encrypt(arboMasterlistData.cp_wash),
        coop_strengthening: encrypt(arboMasterlistData.coop_strengthening),
        vlcep: encrypt(arboMasterlistData.vlcep),
        vlfed: encrypt(arboMasterlistData.vlfed),
        pbd_lawyering: encrypt(arboMasterlistData.pbd_lawyering),
        social_entrep: encrypt(arboMasterlistData.social_entrep),
        sustainable_debris: encrypt(arboMasterlistData.sustainable_debris),
        sustainable_livelihood: encrypt(arboMasterlistData.sustainable_livelihood),
        climate_proofing: encrypt(arboMasterlistData.climate_proofing),
        pahp: encrypt(arboMasterlistData.pahp),
        cbvcd: encrypt(arboMasterlistData.cbvcd),
        fbs: encrypt(arboMasterlistData.fbs),
        pilot_climate_proof: encrypt(arboMasterlistData.pilot_climate_proof),
        cap_pbd: encrypt(arboMasterlistData.cap_pbd),
        card: encrypt(arboMasterlistData.card),
        watsan: encrypt(arboMasterlistData.watsan),
        pablo: encrypt(arboMasterlistData.pablo),
        micoop: encrypt(arboMasterlistData.micoop),
        malp: encrypt(arboMasterlistData.malp),
        csf: encrypt(arboMasterlistData.csf),
        aes: encrypt(arboMasterlistData.aes),
        bds: encrypt(arboMasterlistData.bds),
        pamana: encrypt(arboMasterlistData.pamana),
        bub_dar: encrypt(arboMasterlistData.bub_dar),
        arf: encrypt(arboMasterlistData.arf),
        sbfp: encrypt(arboMasterlistData.sbfp),
        claap: encrypt(arboMasterlistData.claap),
        arbold: encrypt(arboMasterlistData.arbold),
        total_1: encrypt(arboMasterlistData.total_1),
        arcdp_i: encrypt(arboMasterlistData.arcdp_i),
        arcdp_ii: encrypt(arboMasterlistData.arcdp_ii),
        arcp_i: encrypt(arboMasterlistData.arcp_i),
        arcp_ii: encrypt(arboMasterlistData.arcp_ii),
        arisp_i: encrypt(arboMasterlistData.arisp_i),
        arisp_ii: encrypt(arboMasterlistData.arisp_ii),
        arisp_iii: encrypt(arboMasterlistData.arisp_iii),
        bcsea_bazal: encrypt(arboMasterlistData.bcsea_bazal),
        bcsea_umiray: encrypt(arboMasterlistData.bcsea_umiray),
        birasp: encrypt(arboMasterlistData.birasp),
        cmarprp: encrypt(arboMasterlistData.cmarprp),
        converge: encrypt(arboMasterlistData.converge),
        iarcdsp: encrypt(arboMasterlistData.iarcdsp),
        minsaad: encrypt(arboMasterlistData.minsaad),
        nmciremp: encrypt(arboMasterlistData.nmciremp),
        papsra: encrypt(arboMasterlistData.papsra),
        spots: encrypt(arboMasterlistData.spots),
        spots_ii: encrypt(arboMasterlistData.spots_ii),
        starcm: encrypt(arboMasterlistData.starcm),
        tpkp: encrypt(arboMasterlistData.tpkp),
        wmcip: encrypt(arboMasterlistData.wmcip),
        total_2: encrypt(arboMasterlistData.total_2),
        grand_total: encrypt(arboMasterlistData.grand_total),
        remarks: encrypt(arboMasterlistData.remarks),
        status: arboMasterlistData.status,
        time_stamp: arboMasterlistData.time_stamp,
      },
    ];
    arboMasterlist = (await getArboMasterlist(encryptedData)) as CryptGetArboMasterlistResModel[];
  }

  const decryptData = arboMasterlist.map((masterlist) => ({
    id: masterlist.id,
    region_name: decrypt(masterlist.region_name),
    region_code: decrypt(masterlist.region_code),
    province_name: decrypt(masterlist.province_name),
    province_code: decrypt(masterlist.province_code),
    muncity_name: decrypt(masterlist.muncity_name),
    muncity_code: decrypt(masterlist.muncity_code),
    barangay_name: decrypt(masterlist.barangay_name),
    barangay_code: decrypt(masterlist.barangay_code),
    cd: decrypt(masterlist.cd),
    arc_type: decrypt(masterlist.arc_type),
    arc_id: decrypt(masterlist.arc_id),
    arc_name: decrypt(masterlist.arc_name),
    arc_cluster_name: decrypt(masterlist.arc_cluster_name),
    arbo_name: decrypt(masterlist.arbo_name),
    arbo_id: decrypt(masterlist.arbo_id),
    oma_level_2013: decrypt(masterlist.oma_level_2013),
    itema_status_2019: decrypt(masterlist.itema_status_2019),
    itema_level_2019: decrypt(masterlist.itema_level_2019),
    itema_status_current: decrypt(masterlist.itema_status_current),
    itema_level_current: decrypt(masterlist.itema_level_current),
    organization_status: decrypt(masterlist.organization_status),
    organization_type: decrypt(masterlist.organization_type),
    year_organized: decrypt(masterlist.year_organized),
    registering_agency: decrypt(masterlist.registering_agency),
    year_registration: decrypt(masterlist.year_registration),
    baseline_members: decrypt(masterlist.baseline_members),
    baseline_members_male: decrypt(masterlist.baseline_members_male),
    baseline_members_female: decrypt(masterlist.baseline_members_female),
    baseline_total_arbs: decrypt(masterlist.baseline_total_arbs),
    baseline_male_arbs: decrypt(masterlist.baseline_male_arbs),
    baseline_female_arbs: decrypt(masterlist.baseline_female_arbs),
    baseline_total_nonarbs: decrypt(masterlist.baseline_total_nonarbs),
    baseline_male_nonarbs: decrypt(masterlist.baseline_male_nonarbs),
    baseline_female_nonarbs: decrypt(masterlist.baseline_female_nonarbs),
    current_members: decrypt(masterlist.current_members),
    current_members_male: decrypt(masterlist.current_members_male),
    current_members_female: decrypt(masterlist.current_members_female),
    current_total_arbs: decrypt(masterlist.current_total_arbs),
    current_male_arbs: decrypt(masterlist.current_male_arbs),
    current_female_arbs: decrypt(masterlist.current_female_arbs),
    current_total_nonarbs: decrypt(masterlist.current_total_nonarbs),
    current_male_nonarbs: decrypt(masterlist.current_male_nonarbs),
    current_female_nonarbs: decrypt(masterlist.current_female_nonarbs),
    cbu_current: decrypt(masterlist.cbu_current),
    cbu_mem_current: decrypt(masterlist.cbu_mem_current),
    savings_current: decrypt(masterlist.savings_current),
    sav_mem_current: decrypt(masterlist.sav_mem_current),
    assets_current: decrypt(masterlist.assets_current),
    liabilities_current: decrypt(masterlist.liabilities_current),
    services_provided: decrypt(masterlist.services_provided),
    trainings_cap_dev: decrypt(masterlist.trainings_cap_dev),
    apcp: decrypt(masterlist.apcp),
    linksfarm: decrypt(masterlist.linksfarm),
    up_valuing: decrypt(masterlist.up_valuing),
    cp_wash: decrypt(masterlist.cp_wash),
    coop_strengthening: decrypt(masterlist.coop_strengthening),
    vlcep: decrypt(masterlist.vlcep),
    vlfed: decrypt(masterlist.vlfed),
    pbd_lawyering: decrypt(masterlist.pbd_lawyering),
    social_entrep: decrypt(masterlist.social_entrep),
    sustainable_debris: decrypt(masterlist.sustainable_debris),
    sustainable_livelihood: decrypt(masterlist.sustainable_livelihood),
    climate_proofing: decrypt(masterlist.climate_proofing),
    pahp: decrypt(masterlist.pahp),
    cbvcd: decrypt(masterlist.cbvcd),
    fbs: decrypt(masterlist.fbs),
    pilot_climate_proof: decrypt(masterlist.pilot_climate_proof),
    cap_pbd: decrypt(masterlist.cap_pbd),
    card: decrypt(masterlist.card),
    watsan: decrypt(masterlist.watsan),
    pablo: decrypt(masterlist.pablo),
    micoop: decrypt(masterlist.micoop),
    malp: decrypt(masterlist.malp),
    csf: decrypt(masterlist.csf),
    aes: decrypt(masterlist.aes),
    bds: decrypt(masterlist.bds),
    pamana: decrypt(masterlist.pamana),
    bub_dar: decrypt(masterlist.bub_dar),
    arf: decrypt(masterlist.arf),
    sbfp: decrypt(masterlist.sbfp),
    claap: decrypt(masterlist.claap),
    arbold: decrypt(masterlist.arbold),
    total_1: decrypt(masterlist.total_1),
    arcdp_i: decrypt(masterlist.arcdp_i),
    arcdp_ii: decrypt(masterlist.arcdp_ii),
    arcp_i: decrypt(masterlist.arcp_i),
    arcp_ii: decrypt(masterlist.arcp_ii),
    arisp_i: decrypt(masterlist.arisp_i),
    arisp_ii: decrypt(masterlist.arisp_ii),
    arisp_iii: decrypt(masterlist.arisp_iii),
    bcsea_bazal: decrypt(masterlist.bcsea_bazal),
    bcsea_umiray: decrypt(masterlist.bcsea_umiray),
    birasp: decrypt(masterlist.birasp),
    cmarprp: decrypt(masterlist.cmarprp),
    converge: decrypt(masterlist.converge),
    iarcdsp: decrypt(masterlist.iarcdsp),
    minsaad: decrypt(masterlist.minsaad),
    nmciremp: decrypt(masterlist.nmciremp),
    papsra: decrypt(masterlist.papsra),
    spots: decrypt(masterlist.spots),
    spots_ii: decrypt(masterlist.spots_ii),
    starcm: decrypt(masterlist.starcm),
    tpkp: decrypt(masterlist.tpkp),
    wmcip: decrypt(masterlist.wmcip),
    total_2: decrypt(masterlist.total_2),
    grand_total: decrypt(masterlist.grand_total),
    remarks: decrypt(masterlist.remarks),
    status: masterlist.status,
    time_stamp: masterlist.time_stamp,
  }));

  validationInput(getArboMasterlistResModel, decryptData);

  res.status(200).json({
    status: 'success',
    code: 200,
    message: 'successfuly retrieved users',
    data: decryptData,
  });
};

export default getArboMasterlistController;
